[package]
name = "phocus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
crossterm = "0.28.1"
dirs = "5.0.1"
nix = { version = "0.29.0", features = ["user"] }
ratatui = "0.29.0"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
